name = "wipdf"
compatibility_date = "2025-06-21"

[assets]
directory = "./out"

[env.production]
compatibility_date = "2025-06-21"

# For static site deployment
# The build output will be in the 'out' directory after running 'npm run build'
